# Form implementation generated from reading ui file '视图界面.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(625, 445)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"F:\Anylysis_project\pythonProject\logs\figure\软件图标\三维可视化.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        widget.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=widget)
        self.label.setGeometry(QtCore.QRect(-20, -40, 681, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"F:\Anylysis_project\pythonProject\logs\figure\软件图标\背景图.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(parent=widget)
        self.graphicsView.setGeometry(QtCore.QRect(60, 90, 461, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(parent=widget)
        self.label_2.setGeometry(QtCore.QRect(540, 360, 51, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(r"F:\Anylysis_project\pythonProject\logs\figure\校徽图片\05.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=widget)
        self.pushButton.setGeometry(QtCore.QRect(530, 50, 21, 21))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../image/矢量图标/最小化.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(14, 14))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=widget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 50, 21, 21))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../image/矢量图标/关闭.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalSlider = QtWidgets.QSlider(parent=widget)
        self.verticalSlider.setGeometry(QtCore.QRect(550, 110, 18, 160))
        self.verticalSlider.setMouseTracking(False)
        self.verticalSlider.setAcceptDrops(False)
        self.verticalSlider.setStyleSheet("color:white")
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_3 = QtWidgets.QLabel(parent=widget)
        self.label_3.setGeometry(QtCore.QRect(540, 85, 41, 21))
        self.label_3.setStyleSheet("font: 12pt \"阿里妈妈刀隶体\";\n"
"color:white")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(parent=widget)
        self.textEdit.setGeometry(QtCore.QRect(110, 60, 371, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(parent=widget)
        self.label_4.setGeometry(QtCore.QRect(63, 60, 41, 20))
        self.label_4.setStyleSheet("font: 12pt \"阿里妈妈刀隶体\";\n"
"color:white")
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(parent=widget)
        self.radioButton.setGeometry(QtCore.QRect(530, 290, 98, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=widget)
        self.radioButton_2.setGeometry(QtCore.QRect(530, 320, 98, 20))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "3dview"))
        self.label_3.setText(_translate("widget", "缩放："))
        self.label_4.setText(_translate("widget", "描述："))
        self.radioButton.setText(_translate("widget", "地上"))
        self.radioButton_2.setText(_translate("widget", "地下"))
